In [50]:
import numpy as np

In [63]:
# Data
input_data = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
output_labels = np.array([[0,1,1,0]]).T
display(input_data)
display(output_labels)

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

array([[0],
       [1],
       [1],
       [0]])

In [64]:
def activate(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [65]:
synaptic_weights = 2 * np.random.random((3, 1))-1
display(synaptic_weights)

array([[ 0.95885549],
       [ 0.77426728],
       [-0.19014911]])

In [66]:
display(activate(np.dot(input_data,synaptic_weights)))

array([[0.45260544],
       [0.82389659],
       [0.68324099],
       [0.64201445]])

In [67]:
# training
output = activate(np.dot(input_data,synaptic_weights))
error = output_labels-output
display(error)
synaptic_weights += np.dot(input_data.T,error*activate(output,True))

array([[-0.45260544],
       [ 0.17610341],
       [ 0.31675901],
       [-0.64201445]])

In [68]:
for ittr in range(10000):
    output = activate(np.dot(input_data,synaptic_weights))
    error = output_labels-output
    synaptic_weights += np.dot(input_data.T,error*activate(output,True))


In [69]:
# Testing
display(activate(np.dot(np.array([1,0,0]),synaptic_weights)))

array([0.99993707])